# Generated by Django 5.1.2 on 2024-12-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='youtube_video_link',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='team_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
