# Generated by Django 5.1.2 on 2025-02-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_athleteprofile_bio_athleteprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='batting_arm',
            field=models.CharField(default='Unknown', help_text='State of residence/school', max_length=255),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='throwing_arm',
            field=models.CharField(default='Unknown', help_text='State of residence/school', max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="Athlete's biography", null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='height',
            field=models.FloatField(default=6.0, help_text='Height in feet'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='high_school_name',
            field=models.CharField(default='Unknown', help_text="Name of athlete's high school", max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='positions',
            field=models.CharField(default='Unknown', help_text='Sports positions played by athlete', max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Athlete's profile picture", null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='state',
            field=models.CharField(default='Unknown', help_text='State of residence/school', max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this profile', on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='weight',
            field=models.IntegerField(default=150, help_text='Weight in pounds'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='youtube_video_link',
            field=models.URLField(blank=True, help_text="Link to athlete's highlight reel", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="Coach's biography", null=True),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Coach's profile picture", null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='school_name',
            field=models.CharField(default='Unknown', help_text="Name of coach's school/institution", max_length=255),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='state',
            field=models.CharField(default='Unknown', help_text='State of school/institution', max_length=100),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='team_needs',
            field=models.CharField(default='None', help_text='Current team recruitment needs', max_length=255),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this profile', on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Unique name of the role', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions associated with this role', related_name='role_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='scoutprofile',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this profile', on_delete=django.db.models.deletion.CASCADE, related_name='scout_profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's role in the system", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
