# Generated by Django 5.1.7 on 2025-04-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_athleteprofile_batting_arm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='position_within_org',
            field=models.CharField(blank=True, help_text='Position of the coach within the organization', max_length=255, null=True),
        ),
    ]
