# Generated by Django 5.1.7 on 2025-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_athleteprofile_name_coachprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='division',
            field=models.CharField(blank=True, help_text='Division level of the team', max_length=255, null=True),
        ),
    ]
